#include <stdio.h>
#include "bin/board.h"


  /*
int main(int args, char **argv){
	@brief old main made by teachers

	board game = new_game();
	printf("Un plateau est créé.\n");
        piece p = get_piece_from_characteristics(TALL, CIRCULAR, BLUE, HOLLOW);
	enum return_code res = place_piece(game, 2, 0, p);
	if(res == SUCCESS){
		printf("○ □ ○ □  ● ■ ● ■  ○ □ ○ □   ● ■ ● ■.\n");
	}
	else {
		printf("Un problème a eu lieu lors du placement\n");
	}
	destroy_game(game);
	printf("suppression du plateau et sortie\n");
	return 0;
}*/


void print_type_piece(piece p){
/**
 * @brief Prints a symbol representing a
 * 			  piece from a piece object.
 * 			  No return value, only printing.
 * @param piece A piece object
 * */

	switch (piece_color(p)){
		case BLUE :											                                            // If the piece is BLUE (white),
			switch (piece_shape(p)){					                                        // Get the shape of the piece, then print it
				case SQUARE :
					printf("  □  ");
					break;
				case CIRCULAR :
					printf("  ○  ");
					break;
			}
			break;
		case RED:												                                            // If the piece is RED (black),
			switch (piece_shape(p)){					                                        // Get the shape of the piece, then print it
				case SQUARE:
					printf("  ■  ");
					break;
				case CIRCULAR :
          printf("  ●  ");
					break;
			}
			break;
	}
}


void print_row(board game, int row){
/**
 * @brief Displays an entire board row in the terminal
 * @param game A board generated by board.h
 * @param row A row number between 0 and DIMENSION-1
 * */

	piece row_pieces[4] = {get_piece(game, row,0), get_piece(game, row,1), get_piece(game, row,2), get_piece(game, row,3)};
	printf("____________________________\n");

//_________________________________________________________________________________________________________

	for(int j = 0; j < 4; j++){																					           // Displays the Hollow dot "•"
		printf("|");																										             // ift he piece top is HOLLOW
		if(is_occupied(game, row, j) && piece_top(row_pieces[j]) == HOLLOW){
			printf("  •  ");
		}
		else{
			printf("     ");
		}
		printf("|");
	}
	printf("\n");

//_________________________________________________________________________________________________________

	for(int j = 0; j < 4; j++){																			           		// Displays the top part of the piece
		printf("|");																										            // if the piece is TALL
		if(is_occupied(game, row, j) && piece_size(row_pieces[j]) == TALL){
			print_type_piece(row_pieces[j]);
		}
		else{
			printf("     ");
		}
		printf("|");
	}
	printf("\n");

//_________________________________________________________________________________________________________

	for(int j = 0; j < 4; j++){																				          	// Displays the botoom part of the piece
		printf("|");
		if(is_occupied(game, row, j)){
			print_type_piece(row_pieces[j]);
		}
		else{
			printf("     ");
		}
		printf("|");
	}
	printf("\n");
}



void display_board(board game){
/**
 * @brief Clears the terminal and Displays
 * 			 the entire board in the terminal.
 * @param game A 4*4 board to display
 * */
	//printf("\033[2J");
	for(int i = 0; i < 4	; i++){
		print_row(game, i);
	}
	 printf("____________________________\n");   														      // Print bottom line
}



int main(int args, char **argv){
/**
 * @brief Starts a new Quarto game
 * */
	//printf("\033[2J");
	board game = new_game();
	display_board(game);
	return 0;
}
